MA-24269 fix android build break
With the update of android codebase, below build break
can be observed:

src/datastore/fs/nxp_iot_agent_datastore_fs.c:51:74:error: format specifies type 'unsigned int' but the argument has type 'size_t' (aka 'unsigned long') [-Werror,-Wformat]
   51 |         ASSERT_OR_EXIT_MSG(snprintf(filename, filename_size, "%s.%u", basename, index) >= 0, "Error in creating filename string");
      |                                                                  ~~             ^~~~~
      |                                                                  %zu

It seems the build break was caused by the update of default cflags
used by android build system. This commit relax the format check to
make the build pass.

Signed-off-by: Ji Luo <ji.luo@nxp.com>